CREATE INDEX IF NOT EXISTS FOR (n:Module) ON (n.id);
CREATE INDEX IF NOT EXISTS FOR (n:Class) ON (n.id);
CREATE INDEX IF NOT EXISTS FOR (n:Function) ON (n.id);
CREATE INDEX IF NOT EXISTS FOR (n:External) ON (n.id);
CREATE INDEX IF NOT EXISTS FOR (n:VirtualCall) ON (n.id);
MERGE (:Function {id: 'stable:sym:vc_test.py:Strategy.on_tick', name: 'on_tick', qualname: 'Strategy.on_tick', path: 'vc_test.py', lineno: 56, kind: 'method', signature: 'on_tick(self, x: float)', owner_class: 'Strategy', owner_class_id: 'stable:cls:vc_test.py:Strategy', repo_id: 'tests'});
MERGE (:External {id: 'ext:len', name: 'len', namespace: 'len', category: 'stdlib', repo_id: 'tests'});
MERGE (:Function {id: 'stable:sym:vc_test.py:Strategy.helper', name: 'helper', qualname: 'Strategy.helper', path: 'vc_test.py', lineno: 51, kind: 'method', signature: 'helper(self, x: float)', owner_class: 'Strategy', owner_class_id: 'stable:cls:vc_test.py:Strategy', repo_id: 'tests'});
MERGE (:Function {id: 'stable:sym:vc_test.py:util_log', name: 'util_log', qualname: 'util_log', path: 'vc_test.py', lineno: 24, kind: 'function', signature: 'util_log(msg: str)', repo_id: 'tests'});
MERGE (:External {id: 'ext:self.meter.update', name: 'self.meter.update', namespace: 'self', category: 'local_obj', repo_id: 'tests'});
MERGE (:External {id: 'ext:target.update', name: 'target.update', namespace: 'target', category: 'local_obj', repo_id: 'tests'});
MERGE (:External {id: 'ext:print', name: 'print', namespace: 'print', category: 'stdlib', side_effect_category: 'io.console', side_effect_confidence: 0.45, side_effect_evidence: 'heuristic: console/logging call', repo_id: 'tests'});
MERGE (:VirtualCall {id: 'vc:05f9f00142cb', lineno: 64, callee_attr: 'update', receiver_kind: 'self', receiver_name: 'self', full_text: 'self.meter.update', call_kind: 'attr_call', repo_id: 'tests'});
MERGE (:VirtualCall {id: 'vc:6d9007379bb4', lineno: 71, callee_attr: 'update', receiver_kind: 'name', receiver_name: 'target', full_text: 'target.update', call_kind: 'attr_call', repo_id: 'tests'});
MATCH (a {id: 'stable:sym:vc_test.py:Strategy.on_tick'}), (b {id: 'ext:len'}) MERGE (a)-[:CALLS]->(b);
MATCH (a {id: 'stable:sym:vc_test.py:Strategy.on_tick'}), (b {id: 'stable:sym:vc_test.py:Strategy.helper'}) MERGE (a)-[:CALLS]->(b);
MATCH (a {id: 'stable:sym:vc_test.py:Strategy.helper'}), (b {id: 'stable:sym:vc_test.py:util_log'}) MERGE (a)-[:CALLS]->(b);
MATCH (a {id: 'stable:sym:vc_test.py:Strategy.on_tick'}), (b {id: 'ext:self.meter.update'}) MERGE (a)-[:CALLS]->(b);
MATCH (a {id: 'stable:sym:vc_test.py:Strategy.on_tick'}), (b {id: 'ext:target.update'}) MERGE (a)-[:CALLS]->(b);
MATCH (a {id: 'stable:sym:vc_test.py:Strategy.on_tick'}), (b {id: 'stable:sym:vc_test.py:util_log'}) MERGE (a)-[:CALLS]->(b);
MATCH (a {id: 'stable:sym:vc_test.py:util_log'}), (b {id: 'ext:print'}) MERGE (a)-[:CALLS]->(b);
MATCH (a {id: 'stable:sym:vc_test.py:Strategy.on_tick'}), (b {id: 'vc:05f9f00142cb'}) MERGE (a)-[:CALLS_VIRTUAL]->(b);
MATCH (a {id: 'stable:sym:vc_test.py:Strategy.on_tick'}), (b {id: 'vc:6d9007379bb4'}) MERGE (a)-[:CALLS_VIRTUAL]->(b);
